version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ee:17.0.1-ee.0
    container_name: gitlab
    restart: always
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.127.0.0.1.nip.io';
        gitlab_rails['initial_root_password'] = 'DkMP22g2BX';
    ports:
      - '80:80'
      - '443:443'
    shm_size: '256m'
