name: container build
on:
  push:
    branches:
      - '**'
      - '!master'
    tags:
      - '**'
  schedule:
    - cron: '0 0 * * *'
jobs:
  container-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
      - name: container-build
        uses: infinite-automations/full-build-push-action@main
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          checkout-deploy-key: "${{ secrets.COMMIT_KEY }}"
          platforms: "linux/amd64,linux/arm64"
